export const categories = [
    'Web Development',
    'Mobile App Development (Android)',
    'Mobile App Development (iOS)',
    'Game Development',
    'Desktop Software Development',
    'Programming Languages',
    'Database Management',
    'Machine Learning & AI',
    'Cloud Computing',
    'Embedded Systems',
    'DevOps',
    'Networking',
    'Cybersecurity',
    'Data Science',
    'Augmented Reality (AR)',
    'Virtual Reality (VR)',
    'Blockchain Development',
    'Internet of Things (IoT)',
    'Big Data',
    'Bioinformatics',
    'Quantum Computing',
    'Natural Language Processing (NLP)',
    'Robotics',
    'Fintech',
    'Healthtech',
    'Edtech',
    'E-commerce',
    'Social Media Platforms',
    'Digital Marketing',
    'Content Management Systems (CMS)'
    // Add more categories as needed
];