export const frameworks = [
    { name: 'React JS', image: 'react.png' },
    { name: 'Angular JS', image: 'angular.png' },
    { name: 'Vue JS', image: 'vue.png' },
    { name: 'Node JS', image: 'nodejs.png' },
    { name: 'Express JS', image: 'express.png' },
    { name: 'Django', image: 'django.png' },
    { name: 'Flask', image: 'flask.png' },
    { name: 'Ruby on Rails', image: 'rails.png' },
    { name: 'Spring', image: 'spring.png' },
    { name: 'ASP.NET', image: 'aspnet.png' },
    { name: 'Laravel', image: 'laravel.png' },
    { name: 'Symfony', image: 'symfony.png' },
    { name: 'Meteor', image: 'meteor.png' },
    { name: 'Ember JS', image: 'ember.png' },
    { name: 'Backbone JS', image: 'backbone.png' },
    { name: 'jQuery', image: 'jquery.png' },
    { name: 'Bootstrap', image: 'bootstrap.png' },
    { name: 'Tailwind CSS', image: 'tailwind.png' },
    { name: 'Sass', image: 'sass.png' },
    { name: 'Less', image: 'less.png' },
    { name: 'D3 JS', image: 'd3.png' },
    { name: 'Three JS', image: 'three.png' },
    { name: 'Unity', image: 'unity.png' },
    { name: 'Unreal Engine', image: 'unreal.png' },
    { name: 'OpenGL', image: 'opengl.png' },
    { name: 'DirectX', image: 'directx.png' },
    { name: 'C++', image: 'cpp.png' },
    { name: 'Java', image: 'java.png' },
    { name: 'Python', image: 'python.png' },
    { name: 'C#', image: 'csharp.png' },
    { name: 'Ruby', image: 'ruby.png' },
    { name: 'PHP', image: 'php.png' },
    { name: 'JavaScript', image: 'javascript.png' },
    { name: 'TypeScript', image: 'typescript.png' },
    { name: 'HTML', image: 'html.png' },
    { name: 'CSS', image: 'css.png' },
    { name: 'FastAPI', image: 'css.png' },
    { name: 'Next JS', image: 'css.png' },
    { name: 'Flutter', image: 'css.png' },
    { name: 'Swift', image: 'css.png' },
    { name: 'Kotlin', image: 'css.png' }
    

];